OPENAI_API_KEY="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"
ritter_pinecone_api = "5fd10d45-d8a6-4dc0-8436-d54afbe8ba75"
fair_pinecone_env = "northamerica-northeast1-gcp"
fair_pinecone_index = "canopy--fair"